### ISSUE TITLE
Proper realtime comment updates

### ISSUE THREAD

**Issue by arunoda** [kadirahq/storybook-addon-comments#11]
We need to check for new comments periodically. That's okay for now.
Later on, we need to do it with some realtime API or some hack in the comments DB.

**Comment by arunoda** [comment]
## Tasks
- [x] Move datastore into a new class - https://github.com/kadirahq/storybook-addon-comments/pull/18
- [ ] Add streaming support to the backend.
- [ ] Add streaming support to the cloud database.
- [ ] Send new comments over the stream.
